inbound:
  jobs:
    aiNews:
      enabled: false
      executeOnStartup: true
    cryptoNews:
      enabled: false
      executeOnStartup: true
    developmentNews:
      enabled: false
      executeOnStartup: true
    financeNews:
      enabled: false
      executeOnStartup: true
    spaceEvents:
      enabled: false
      executeOnStartup: true
    technologyEvents:
      enabled: false
      executeOnStartup: true
outbound:
  discord:
    channels:
      ai: '__tests__'
      development: '__tests__'
      crypto: '__tests__'
      finance: '__tests__'
      space: '__tests__'
      technology: '__tests__'
